version: "3"
services:
  instagram-clone-mysql:
    image: mysql:5.6
    container_name: instagram-clone-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "instagramclonedb"
      MYSQL_USER: "instagramclone"
      MYSQL_PASSWORD: "123123"
      MYSQL_ROOT_PASSWORD: "123123"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8888:8080
