name: Heroku Awake
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  awake:
    runs-on: ubuntu-latest
    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: https://instagram-clone-5erver.herokuapp.com/actuator/health
